config/routes.rb
Rails.application.routes.draw do
  # root 'home#index'
  # esources :posts

  resources :products

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show

  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path
    else
      redirect_to @product
    end

  end


  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :amount, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1> Posts </h1>

<% @posts.each do |post| %>
  <h3> <%= link_to post.title, post %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFistApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_product.html.erb
<%= form_with(model: @product) do |form|%>
    <%= form.label :name%>
    <%= form.text_field :name%>
    <%= form.label :amount%>
    <%= form.number_field :amount%>
    <%= form.label :price%>
    <%= form.number_field :price%>

    <%= form.submit "save"%>
<% end %>

app/views/products/edit.html.erb
<%= render 'product' %>

<%= link_to "back", products_path %>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <p>
    <b>Name:</b>
    <%= product.name %>
    <b>Quantidade:</b>
    <%= product.amount %>
    <b>Preço:</b>
    <%= product.price %>

    <%= link_to "show", product %>
    <%= link_to "edit", edit_product_path(product) %>
    <%= button_to "delete", product, method: :delete, form: {data: {turbo_confirm: "Você tem certeza que quer apagar?"}} %>
  </p>
<% end %>

app/views/products/new.html.erb
<%= render 'product' %>

<%= link_to "back", products_path %>

app/views/products/show.html.erb
<p>
Nome:
<%= @product.name %>
Quantidade:
<%= @product.amount %>
Preço:
<%= @product.price %>

<%= link_to "edit", edit_product_path(@product) %>
<%= button_to "delete", @product, method: :delete, form: {data: {turbo_confirm: "Você tem certeza que quer apagar?"}} %>

</p>